# Upload YAML
POST http://localhost:8080/v1/fragments
Content-Type: application/yaml
[BasicAuth]
user1@email.com:password1

`name: Alice\nscore: 95`

HTTP/1.1 201
[Asserts]
# The Location header should look like what we expect (including the fragment id)
header "Location" matches "^http:\/\/localhost:8080\/v1\/fragments\/[A-Za-z0-9_-]+$"
jsonpath "$.status" == "ok"
# Our fragment ids use UUIDs, see https://ihateregex.io/expr/uuid/
jsonpath "$.fragment.id" matches "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
# Our ownerId hash is a hex encoded string
jsonpath "$.fragment.ownerId" matches "^[0-9a-fA-F]+$"
# Basic check for the presence of created and updated date strings.
# You could also write a regex for this and use matches
jsonpath "$.fragment.created" isString
jsonpath "$.fragment.updated" isString
jsonpath "$.fragment.type" == "application/yaml"
jsonpath "$.fragment.size" == 21

[Captures]
url: header "Location"

# Convert YAML to Plain Text
GET {{url}}.txt
[BasicAuth]
user1@email.com:password1

HTTP/1.1 200
Content-Length: 21
[Asserts]
header "Content-Type" startsWith "text/plain"
body == "name: Alice\nscore: 95"

# Convert YAML to JSON
GET {{url}}.json
[BasicAuth]
user1@email.com:password1

HTTP/1.1 200
Content-Length: 36
[Asserts]
header "Content-Type" startsWith "application/json"
jsonpath "$.name" == "Alice"
jsonpath "$.score" == 95


# Convert YAML to YAML 
GET {{url}}.yaml
[BasicAuth]
user1@email.com:password1

HTTP/1.1 200
Content-Length: 21
[Asserts]
header "Content-Type" startsWith "application/yaml"
body == "name: Alice\nscore: 95"
